### ISSUE TITLE
jar执行方式，识别图片的时候必须先训练，请问如何解决

### ISSUE THREAD

**Issue by shangzm** [InitAction/car-OCR#1]
eclipse导入包识别的时候能够正确识别，但是当jar包方式执行的时候，始终需要先训练才行，请问如何训练？报错信息如下：java.lang.RuntimeException: ..\..\..\..\opencv\modules\ml\src\svm.cpp:2131: error: (-5) The SVM should be trained first in function CvSVM::predict

**Comment by InitAction** [comment]
可以在自己的数据上训练SVM模型
https://github.com/InitAction/car-OCR/blob/4a32326bd663f12e642c969b3979594332189f51/src/main/java/org/easypr/train/SVMTrain.java#L234
